# Copyright 2018-2023 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that provides the Open Liberty and WebSphere Liberty runtimes."
  homepage = "https://github.com/paketo-buildpacks/liberty"
  id = "paketo-buildpacks/liberty"
  keywords = ["java", "javaee", "liberty"]
  name = "Paketo Buildpack for Liberty"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/liberty/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/main", "linux/amd64/bin/helper", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/main", "linux/arm64/bin/helper", "buildpack.toml", "templates/server.tmpl", "templates/app.tmpl", "templates/features.tmpl", "templates/expose-default-endpoint.xml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "the application server to use"
    name = "BP_JAVA_APP_SERVER"

  [[metadata.configurations]]
    build = true
    default = "ol"
    description = "Install type of Liberty"
    launch = false
    name = "BP_LIBERTY_INSTALL_TYPE"

  [[metadata.configurations]]
    build = true
    default = "*"
    description = "Which version of the Liberty runtime to install"
    launch = false
    name = "BP_LIBERTY_VERSION"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "The Liberty profile to install"
    launch = false
    name = "BP_LIBERTY_PROFILE"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "Name of the server to use"
    launch = true
    name = "BP_LIBERTY_SERVER_NAME"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "Context root to use for app"
    launch = false
    name = "BP_LIBERTY_CONTEXT_ROOT"

  [[metadata.configurations]]
    build = false
    default = ""
    description = "Sets the logging level"
    launch = true
    name = "BPL_LIBERTY_LOG_LEVEL"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "A space separated list of liberty features to install."
    launch = false
    name = "BP_LIBERTY_FEATURES"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "Disable running the feature installer."
    launch = false
    name = "BP_LIBERTY_FEATURE_INSTALL_DISABLED"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "OpenJ9 only: Disable building the shared class cache."
    launch = false
    name = "BP_LIBERTY_SCC_DISABLED"

  [[metadata.configurations]]
    build = true
    default = "100"
    description = "OpenJ9 only: Size to use for the shared class cache."
    launch = false
    name = "BP_LIBERTY_SCC_SIZE_MB"

  [[metadata.configurations]]
    build = true
    default = "1"
    description = "OpenJ9 only: Number of iterations to cycle the server when building the shared class cache."
    launch = false
    name = "BP_LIBERTY_SCC_NUM_ITERATIONS"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "OpenJ9 only: Disable trimming the size of the shared class cache."
    launch = false
    name = "BP_LIBERTY_SCC_TRIM_SIZE_DISABLED"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:26.0.0.3:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-full"
    name = "Open Liberty (All Features)"
    purl = "pkg:maven/io.openliberty/openliberty-runtime@26.0.0.3"
    sha256 = "bf394f83897a5aa4d0564604637e934c8f64b9fcb06a8dfcec2a49feed951778"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-26.0.0.3.tar.gz"
    source-sha256 = "bff6a34b74ab23e1302fbfcf85bcfa60214008c9c41d07a491d314c155549545"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-runtime/26.0.0.3/openliberty-runtime-26.0.0.3.zip"
    version = "26.0.3"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:26.0.0.3:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-jakartaee10"
    name = "Open Liberty (Jakarta EE10)"
    purl = "pkg:maven/io.openliberty/openliberty-jakartaee10@26.0.0.3"
    sha256 = "a2e5e5a8dd026afd25ded42da62a61afee2efd33e1cfdf5983bc533e2830d395"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-26.0.0.3.tar.gz"
    source-sha256 = "bff6a34b74ab23e1302fbfcf85bcfa60214008c9c41d07a491d314c155549545"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-jakartaee10/26.0.0.3/openliberty-jakartaee10-26.0.0.3.zip"
    version = "26.0.3"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:26.0.0.3:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-javaee8"
    name = "Open Liberty (Java EE8)"
    purl = "pkg:maven/io.openliberty/openliberty-javaee8@26.0.0.3"
    sha256 = "8cd26639ea228cdb41113672b6c2af7fe536777d69fbab06aa63d9ac0438856c"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-26.0.0.3.tar.gz"
    source-sha256 = "bff6a34b74ab23e1302fbfcf85bcfa60214008c9c41d07a491d314c155549545"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-javaee8/26.0.0.3/openliberty-javaee8-26.0.0.3.zip"
    version = "26.0.3"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:26.0.0.3:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-webProfile10"
    name = "Open Liberty (Web Profile 10)"
    purl = "pkg:maven/io.openliberty/openliberty-webProfile10@26.0.0.3"
    sha256 = "c45ea8a64defedec1b0a26898301a266b01e2ed35ddb9448780199ef95b466e7"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-26.0.0.3.tar.gz"
    source-sha256 = "bff6a34b74ab23e1302fbfcf85bcfa60214008c9c41d07a491d314c155549545"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-webProfile10/26.0.0.3/openliberty-webProfile10-26.0.0.3.zip"
    version = "26.0.3"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:26.0.0.3:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-webProfile8"
    name = "Open Liberty (Web Profile 8)"
    purl = "pkg:maven/io.openliberty/openliberty-webProfile8@26.0.0.3"
    sha256 = "e1421387b006c06cfb67948a318f8ce5b68766d7a82d3efcc6cd8081164d2310"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-26.0.0.3.tar.gz"
    source-sha256 = "bff6a34b74ab23e1302fbfcf85bcfa60214008c9c41d07a491d314c155549545"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-webProfile8/26.0.0.3/openliberty-webProfile8-26.0.0.3.zip"
    version = "26.0.3"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:26.0.0.3:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-microProfile4"
    name = "Open Liberty (Micro Profile 4)"
    purl = "pkg:maven/io.openliberty/openliberty-microProfile4@26.0.0.3"
    sha256 = "f838a95121d28469cd277a68542de9769105c4e74e79c84e14276e32d9af6dca"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-26.0.0.3.tar.gz"
    source-sha256 = "bff6a34b74ab23e1302fbfcf85bcfa60214008c9c41d07a491d314c155549545"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-microProfile4/26.0.0.3/openliberty-microProfile4-26.0.0.3.zip"
    version = "26.0.3"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:26.0.0.3:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-kernel"
    name = "Open Liberty (Kernel)"
    purl = "pkg:maven/io.openliberty/openliberty-kernel@26.0.0.3"
    sha256 = "d5905bcff2e1cc4bb969148e86f7e9b3a7e54606d9623fa2f70ed8cdb8545345"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-26.0.0.3.tar.gz"
    source-sha256 = "bff6a34b74ab23e1302fbfcf85bcfa60214008c9c41d07a491d314c155549545"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-kernel/26.0.0.3/openliberty-kernel-26.0.0.3.zip"
    version = "26.0.3"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:26.0.0.3:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-microProfile7"
    name = "Open Liberty (Micro Profile 7)"
    purl = "pkg:maven/io.openliberty/openliberty-microProfile7@26.0.0.3"
    sha256 = "66e15e7c5f49b673be246a8cafbe2844a07ac2a788c8acfa5be16cd9c8cc765d"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-26.0.0.3.tar.gz"
    source-sha256 = "bff6a34b74ab23e1302fbfcf85bcfa60214008c9c41d07a491d314c155549545"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-microProfile7/26.0.0.3/openliberty-microProfile7-26.0.0.3.zip"
    version = "26.0.3"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:26.0.0.3:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-kernel"
    name = "WebSphere Liberty (Kernel)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-kernel@26.0.0.3"
    sha256 = "64226539d8e193a939b98a7882a39e3acdcf35bab3ce08a2df469f87509b38dd"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-kernel/26.0.0.3/wlp-kernel-26.0.0.3.zip"
    version = "26.0.3"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:26.0.0.4:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-jakartaee10"
    name = "WebSphere Liberty (Jakarta EE9)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-jakartaee10@26.0.0.4"
    sha256 = "fbe6ea7eb03683ee725990c37e28d1990206de5808209437903cbee939686ded"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-jakartaee10/26.0.0.4/wlp-jakartaee10-26.0.0.4.zip"
    version = "26.0.4"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:26.0.0.3:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-javaee8"
    name = "WebSphere Liberty (Java EE8)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-javaee8@26.0.0.3"
    sha256 = "769e0bd6113c80a3777c8cf4d176447b752087cc1e5f773e4d5ac6e14744c7de"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-javaee8/26.0.0.3/wlp-javaee8-26.0.0.3.zip"
    version = "26.0.3"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:26.0.0.3:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-javaee7"
    name = "WebSphere Liberty (Java EE7)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-javaee7@26.0.0.3"
    sha256 = "83ff919bce121fef0a74fbb92b3c692f7ba9f75eaa43ea908246d65f027f5f26"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-javaee7/26.0.0.3/wlp-javaee7-26.0.0.3.zip"
    version = "26.0.3"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:26.0.0.3:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-webProfile10"
    name = "WebSphere Liberty (Web Profile 10)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-webProfile10@26.0.0.3"
    sha256 = "d62deaf9dbad1dfd2503c72d3f8876e64c8e08d5a5caaf86d7809cf7d22671c5"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-webProfile10/26.0.0.3/wlp-webProfile10-26.0.0.3.zip"
    version = "26.0.3"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:26.0.0.3:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-webProfile8"
    name = "WebSphere Liberty (Web Profile 8)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-webProfile8@26.0.0.3"
    sha256 = "6900f1cdd60b42318e1de899c9faf70b310a664916af1b14031f563542a04457"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-webProfile8/26.0.0.3/wlp-webProfile8-26.0.0.3.zip"
    version = "26.0.3"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:26.0.0.3:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-webProfile7"
    name = "WebSphere Liberty (Web Profile 7)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-webProfile7@26.0.0.3"
    sha256 = "c56f7a0e1e0adc4d350770de1845ae81cdf27b83f3f1824dbb6676c51641b2d7"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-webProfile7/26.0.0.3/wlp-webProfile7-26.0.0.3.zip"
    version = "26.0.3"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
