# Copyright 2018-2023 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that provides the Open Liberty and WebSphere Liberty runtimes."
  homepage = "https://github.com/paketo-buildpacks/liberty"
  id = "paketo-buildpacks/liberty"
  keywords = ["java", "javaee", "liberty"]
  name = "Paketo Buildpack for Liberty"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/liberty/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/main", "linux/amd64/bin/helper", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/main", "linux/arm64/bin/helper", "buildpack.toml", "templates/server.tmpl", "templates/app.tmpl", "templates/features.tmpl", "templates/expose-default-endpoint.xml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "the application server to use"
    name = "BP_JAVA_APP_SERVER"

  [[metadata.configurations]]
    build = true
    default = "ol"
    description = "Install type of Liberty"
    launch = false
    name = "BP_LIBERTY_INSTALL_TYPE"

  [[metadata.configurations]]
    build = true
    default = "*"
    description = "Which version of the Liberty runtime to install"
    launch = false
    name = "BP_LIBERTY_VERSION"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "The Liberty profile to install"
    launch = false
    name = "BP_LIBERTY_PROFILE"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "Name of the server to use"
    launch = true
    name = "BP_LIBERTY_SERVER_NAME"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "Context root to use for app"
    launch = false
    name = "BP_LIBERTY_CONTEXT_ROOT"

  [[metadata.configurations]]
    build = false
    default = ""
    description = "Sets the logging level"
    launch = true
    name = "BPL_LIBERTY_LOG_LEVEL"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "A space separated list of liberty features to install."
    launch = false
    name = "BP_LIBERTY_FEATURES"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "Disable running the feature installer."
    launch = false
    name = "BP_LIBERTY_FEATURE_INSTALL_DISABLED"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "OpenJ9 only: Disable building the shared class cache."
    launch = false
    name = "BP_LIBERTY_SCC_DISABLED"

  [[metadata.configurations]]
    build = true
    default = "100"
    description = "OpenJ9 only: Size to use for the shared class cache."
    launch = false
    name = "BP_LIBERTY_SCC_SIZE_MB"

  [[metadata.configurations]]
    build = true
    default = "1"
    description = "OpenJ9 only: Number of iterations to cycle the server when building the shared class cache."
    launch = false
    name = "BP_LIBERTY_SCC_NUM_ITERATIONS"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "OpenJ9 only: Disable trimming the size of the shared class cache."
    launch = false
    name = "BP_LIBERTY_SCC_TRIM_SIZE_DISABLED"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:26.0.0.2:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-full"
    name = "Open Liberty (All Features)"
    purl = "pkg:maven/io.openliberty/openliberty-runtime@26.0.0.2"
    sha256 = "6f47b9c9f2f1c6af546c391ad80da3e0548a285ee3d29234ece6da7c0351a377"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-26.0.0.2.tar.gz"
    source-sha256 = "370f4051ce17d83f547e6fcba39ce7734df8ddeb1cd892b8087cd9a706e8bea5"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-runtime/26.0.0.2/openliberty-runtime-26.0.0.2.zip"
    version = "26.0.2"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:26.0.0.2:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-jakartaee10"
    name = "Open Liberty (Jakarta EE10)"
    purl = "pkg:maven/io.openliberty/openliberty-jakartaee10@26.0.0.2"
    sha256 = "b20790dab5eeb2a8b531ba9c2bca0a8377a88cf53d3d49f65a25aed3acb2bdb6"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-26.0.0.2.tar.gz"
    source-sha256 = "370f4051ce17d83f547e6fcba39ce7734df8ddeb1cd892b8087cd9a706e8bea5"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-jakartaee10/26.0.0.2/openliberty-jakartaee10-26.0.0.2.zip"
    version = "26.0.2"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:26.0.0.2:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-javaee8"
    name = "Open Liberty (Java EE8)"
    purl = "pkg:maven/io.openliberty/openliberty-javaee8@26.0.0.2"
    sha256 = "0fad63e389f9ec38ff0444661960d70988f7064a459b263ffe8006f58347bc62"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-26.0.0.2.tar.gz"
    source-sha256 = "370f4051ce17d83f547e6fcba39ce7734df8ddeb1cd892b8087cd9a706e8bea5"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-javaee8/26.0.0.2/openliberty-javaee8-26.0.0.2.zip"
    version = "26.0.2"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:26.0.0.3:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-webProfile10"
    name = "Open Liberty (Web Profile 10)"
    purl = "pkg:maven/io.openliberty/openliberty-webProfile10@26.0.0.3"
    sha256 = "c45ea8a64defedec1b0a26898301a266b01e2ed35ddb9448780199ef95b466e7"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-26.0.0.3.tar.gz"
    source-sha256 = "bff6a34b74ab23e1302fbfcf85bcfa60214008c9c41d07a491d314c155549545"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-webProfile10/26.0.0.3/openliberty-webProfile10-26.0.0.3.zip"
    version = "26.0.3"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:26.0.0.2:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-webProfile8"
    name = "Open Liberty (Web Profile 8)"
    purl = "pkg:maven/io.openliberty/openliberty-webProfile8@26.0.0.2"
    sha256 = "348481bdec5e95b8d6c56ae1346d38a498b77939cae227315a04633dcfc67594"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-26.0.0.2.tar.gz"
    source-sha256 = "370f4051ce17d83f547e6fcba39ce7734df8ddeb1cd892b8087cd9a706e8bea5"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-webProfile8/26.0.0.2/openliberty-webProfile8-26.0.0.2.zip"
    version = "26.0.2"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:26.0.0.2:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-microProfile4"
    name = "Open Liberty (Micro Profile 4)"
    purl = "pkg:maven/io.openliberty/openliberty-microProfile4@26.0.0.2"
    sha256 = "8a0cbd03234f3fe1fbbd70902e25242cdaa640f0dc4c72dfe490b8077a3f4512"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-26.0.0.2.tar.gz"
    source-sha256 = "370f4051ce17d83f547e6fcba39ce7734df8ddeb1cd892b8087cd9a706e8bea5"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-microProfile4/26.0.0.2/openliberty-microProfile4-26.0.0.2.zip"
    version = "26.0.2"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:26.0.0.2:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-kernel"
    name = "Open Liberty (Kernel)"
    purl = "pkg:maven/io.openliberty/openliberty-kernel@26.0.0.2"
    sha256 = "55d809a06dd93aef9657914de8ab5bf7d00ea35d37a67cd05682faab48ef221d"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-26.0.0.2.tar.gz"
    source-sha256 = "370f4051ce17d83f547e6fcba39ce7734df8ddeb1cd892b8087cd9a706e8bea5"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-kernel/26.0.0.2/openliberty-kernel-26.0.0.2.zip"
    version = "26.0.2"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:26.0.0.2:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-microProfile7"
    name = "Open Liberty (Micro Profile 7)"
    purl = "pkg:maven/io.openliberty/openliberty-microProfile7@26.0.0.2"
    sha256 = "8bd61c4b9a87fb70560457afe928759bea65f5ee93225a50e9a1038f742eb023"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-26.0.0.2.tar.gz"
    source-sha256 = "370f4051ce17d83f547e6fcba39ce7734df8ddeb1cd892b8087cd9a706e8bea5"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-microProfile7/26.0.0.2/openliberty-microProfile7-26.0.0.2.zip"
    version = "26.0.2"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:26.0.0.2:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-kernel"
    name = "WebSphere Liberty (Kernel)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-kernel@26.0.0.2"
    sha256 = "9f63be72bcd6f6e62048a6491d567cd18235ac9e976f05aa869b9a1443c5ffec"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-kernel/26.0.0.2/wlp-kernel-26.0.0.2.zip"
    version = "26.0.2"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:26.0.0.2:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-jakartaee10"
    name = "WebSphere Liberty (Jakarta EE9)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-jakartaee10@26.0.0.2"
    sha256 = "2d6621cb3df2d099f6576737aa6b7f62a56abebd025463c4ef59733854c5e730"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-jakartaee10/26.0.0.2/wlp-jakartaee10-26.0.0.2.zip"
    version = "26.0.2"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:26.0.0.2:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-javaee8"
    name = "WebSphere Liberty (Java EE8)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-javaee8@26.0.0.2"
    sha256 = "477cda37932570730708d517336130eaeb2ea9830cebfdc16c74f7b9e5fceee9"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-javaee8/26.0.0.2/wlp-javaee8-26.0.0.2.zip"
    version = "26.0.2"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:26.0.0.2:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-javaee7"
    name = "WebSphere Liberty (Java EE7)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-javaee7@26.0.0.2"
    sha256 = "f63b38e68ac7682df1dd8a7d45f571816b5ef1eeec4bf1737d407d2fafb610c6"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-javaee7/26.0.0.2/wlp-javaee7-26.0.0.2.zip"
    version = "26.0.2"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:26.0.0.2:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-webProfile10"
    name = "WebSphere Liberty (Web Profile 10)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-webProfile10@26.0.0.2"
    sha256 = "4514a054c94846ce44b0f6e066b6e7e6a897a616f623187d8108c91eea8de70a"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-webProfile10/26.0.0.2/wlp-webProfile10-26.0.0.2.zip"
    version = "26.0.2"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:26.0.0.2:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-webProfile8"
    name = "WebSphere Liberty (Web Profile 8)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-webProfile8@26.0.0.2"
    sha256 = "e61212865bfb6522f24197746f2657e1bd16ffcf66114652301b2dd2dd95926c"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-webProfile8/26.0.0.2/wlp-webProfile8-26.0.0.2.zip"
    version = "26.0.2"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:26.0.0.2:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-webProfile7"
    name = "WebSphere Liberty (Web Profile 7)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-webProfile7@26.0.0.2"
    sha256 = "d5f3de10af7747e5c0be5cdecb5441678eb0d96993a5fd724147c56d876812e3"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-webProfile7/26.0.0.2/wlp-webProfile7-26.0.0.2.zip"
    version = "26.0.2"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
