# Copyright 2018-2023 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that provides the Open Liberty and WebSphere Liberty runtimes."
  homepage = "https://github.com/paketo-buildpacks/liberty"
  id = "paketo-buildpacks/liberty"
  keywords = ["java", "javaee", "liberty"]
  name = "Paketo Buildpack for Liberty"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/liberty/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/main", "linux/amd64/bin/helper", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/main", "linux/arm64/bin/helper", "buildpack.toml", "templates/server.tmpl", "templates/app.tmpl", "templates/features.tmpl", "templates/expose-default-endpoint.xml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "the application server to use"
    name = "BP_JAVA_APP_SERVER"

  [[metadata.configurations]]
    build = true
    default = "ol"
    description = "Install type of Liberty"
    launch = false
    name = "BP_LIBERTY_INSTALL_TYPE"

  [[metadata.configurations]]
    build = true
    default = "*"
    description = "Which version of the Liberty runtime to install"
    launch = false
    name = "BP_LIBERTY_VERSION"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "The Liberty profile to install"
    launch = false
    name = "BP_LIBERTY_PROFILE"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "Name of the server to use"
    launch = true
    name = "BP_LIBERTY_SERVER_NAME"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "Context root to use for app"
    launch = false
    name = "BP_LIBERTY_CONTEXT_ROOT"

  [[metadata.configurations]]
    build = false
    default = ""
    description = "Sets the logging level"
    launch = true
    name = "BPL_LIBERTY_LOG_LEVEL"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "A space separated list of liberty features to install."
    launch = false
    name = "BP_LIBERTY_FEATURES"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "Disable running the feature installer."
    launch = false
    name = "BP_LIBERTY_FEATURE_INSTALL_DISABLED"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "OpenJ9 only: Disable building the shared class cache."
    launch = false
    name = "BP_LIBERTY_SCC_DISABLED"

  [[metadata.configurations]]
    build = true
    default = "100"
    description = "OpenJ9 only: Size to use for the shared class cache."
    launch = false
    name = "BP_LIBERTY_SCC_SIZE_MB"

  [[metadata.configurations]]
    build = true
    default = "1"
    description = "OpenJ9 only: Number of iterations to cycle the server when building the shared class cache."
    launch = false
    name = "BP_LIBERTY_SCC_NUM_ITERATIONS"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "OpenJ9 only: Disable trimming the size of the shared class cache."
    launch = false
    name = "BP_LIBERTY_SCC_TRIM_SIZE_DISABLED"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:26.0.0.5:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-full"
    name = "Open Liberty (All Features)"
    purl = "pkg:maven/io.openliberty/openliberty-runtime@26.0.0.5"
    sha256 = "78c682015b55cac0045e42cd7f71499cc34497af37cda8cea8747396c61ac1bc"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-26.0.0.5.tar.gz"
    source-sha256 = "c3bcbadc2d71a6d6b131bb00fe9327a1ddb8a46a059fcb051349cd9017058352"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-runtime/26.0.0.5/openliberty-runtime-26.0.0.5.zip"
    version = "26.0.5"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:26.0.0.5:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-jakartaee11"
    name = "Open Liberty (Jakarta EE11)"
    purl = "pkg:maven/io.openliberty/openliberty-jakartaee11@26.0.0.5"
    sha256 = "4648a89b7b16297bfa70c0a666963695c59a55331cc94e96a1d47ed4cc63b110"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-26.0.0.5.tar.gz"
    source-sha256 = "c3bcbadc2d71a6d6b131bb00fe9327a1ddb8a46a059fcb051349cd9017058352"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-jakartaee11/26.0.0.5/openliberty-jakartaee11-26.0.0.5.zip"
    version = "26.0.5"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:26.0.0.5:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-javaee8"
    name = "Open Liberty (Java EE8)"
    purl = "pkg:maven/io.openliberty/openliberty-javaee8@26.0.0.5"
    sha256 = "3bddc69e4f3ff0300b75243581af9d2870a9944861c22e026b8e170eab7bd3f5"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-26.0.0.5.tar.gz"
    source-sha256 = "c3bcbadc2d71a6d6b131bb00fe9327a1ddb8a46a059fcb051349cd9017058352"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-javaee8/26.0.0.5/openliberty-javaee8-26.0.0.5.zip"
    version = "26.0.5"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:26.0.0.6:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-webProfile11"
    name = "Open Liberty (Web Profile 11)"
    purl = "pkg:maven/io.openliberty/openliberty-webProfile11@26.0.0.6"
    sha256 = "f1ed3fc17e53ccabcdd5cc452e1be71598a57c80dbe48a82e062663a00141e75"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-26.0.0.6.tar.gz"
    source-sha256 = "d555392c7af30ab289c89c5ac7cb8ce10bd87dcaa215bea62c20a5dea453b6d9"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-webProfile11/26.0.0.6/openliberty-webProfile11-26.0.0.6.zip"
    version = "26.0.6"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:26.0.0.5:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-webProfile8"
    name = "Open Liberty (Web Profile 8)"
    purl = "pkg:maven/io.openliberty/openliberty-webProfile8@26.0.0.5"
    sha256 = "5914258c0900fac7f9187ec3299b980fc4b7dbd438fff2e69f7617acbc4c5ecb"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-26.0.0.5.tar.gz"
    source-sha256 = "c3bcbadc2d71a6d6b131bb00fe9327a1ddb8a46a059fcb051349cd9017058352"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-webProfile8/26.0.0.5/openliberty-webProfile8-26.0.0.5.zip"
    version = "26.0.5"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:26.0.0.5:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-microProfile4"
    name = "Open Liberty (Micro Profile 4)"
    purl = "pkg:maven/io.openliberty/openliberty-microProfile4@26.0.0.5"
    sha256 = "eacd8cad8857631d1c7e138bee12bb12f73c24b61fca3c7e0b9db3ca1812581a"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-26.0.0.5.tar.gz"
    source-sha256 = "c3bcbadc2d71a6d6b131bb00fe9327a1ddb8a46a059fcb051349cd9017058352"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-microProfile4/26.0.0.5/openliberty-microProfile4-26.0.0.5.zip"
    version = "26.0.5"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:26.0.0.6:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-kernel"
    name = "Open Liberty (Kernel)"
    purl = "pkg:maven/io.openliberty/openliberty-kernel@26.0.0.6"
    sha256 = "aceb02d9737231b9a5b01ae609b6f206fa75575ff74d8d8427c6979ca0b2c06a"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-26.0.0.6.tar.gz"
    source-sha256 = "d555392c7af30ab289c89c5ac7cb8ce10bd87dcaa215bea62c20a5dea453b6d9"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-kernel/26.0.0.6/openliberty-kernel-26.0.0.6.zip"
    version = "26.0.6"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:open_liberty:26.0.0.5:*:*:*:*:*:*:*"]
    id = "open-liberty-runtime-microProfile7"
    name = "Open Liberty (Micro Profile 7)"
    purl = "pkg:maven/io.openliberty/openliberty-microProfile7@26.0.0.5"
    sha256 = "ca8ce66707d13ab39f90bc292986d0d1116841ab5a6fd659a4a10689d5362e0a"
    source = "https://github.com/OpenLiberty/open-liberty/archive/refs/tags/gm-26.0.0.5.tar.gz"
    source-sha256 = "c3bcbadc2d71a6d6b131bb00fe9327a1ddb8a46a059fcb051349cd9017058352"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-microProfile7/26.0.0.5/openliberty-microProfile7-26.0.0.5.zip"
    version = "26.0.5"

    [[metadata.dependencies.licenses]]
      type = "EPL-2.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:26.0.0.5:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-kernel"
    name = "WebSphere Liberty (Kernel)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-kernel@26.0.0.5"
    sha256 = "4ce253d6896e137008647577cda984a9a4da82e4caf044608ef0ee84312a5371"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-kernel/26.0.0.5/wlp-kernel-26.0.0.5.zip"
    version = "26.0.5"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:26.0.0.5:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-jakartaee11"
    name = "WebSphere Liberty (Jakarta EE11)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-jakartaee11@26.0.0.5"
    sha256 = "d7479c5c76ccb811286721c40c18ce4573942b979b277e77805a27a50bc8f60a"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-jakartaee11/26.0.0.5/wlp-jakartaee11-26.0.0.5.zip"
    version = "26.0.5"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:26.0.0.5:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-javaee8"
    name = "WebSphere Liberty (Java EE8)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-javaee8@26.0.0.5"
    sha256 = "f14b1826b93f0bdb1b32607ce75194bc6ed54ce535c7b1e71e96eaca3348f7bc"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-javaee8/26.0.0.5/wlp-javaee8-26.0.0.5.zip"
    version = "26.0.5"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:26.0.0.6:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-javaee7"
    name = "WebSphere Liberty (Java EE7)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-javaee7@26.0.0.6"
    sha256 = "55ae7d5600366345311fb64ea819a133d7a12f8aa1d2a4738ecebc3967368e27"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-javaee7/26.0.0.6/wlp-javaee7-26.0.0.6.zip"
    version = "26.0.6"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:26.0.0.5:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-webProfile11"
    name = "WebSphere Liberty (Web Profile 11)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-webProfile11@26.0.0.5"
    sha256 = "285a59df4f5a8141879475a44814bb34e4a12eada84015bf0af6e6843353e3a5"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-webProfile11/26.0.0.5/wlp-webProfile11-26.0.0.5.zip"
    version = "26.0.5"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:26.0.0.5:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-webProfile8"
    name = "WebSphere Liberty (Web Profile 8)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-webProfile8@26.0.0.5"
    sha256 = "6f4331d55973555f954a4a6acb76865fc358fc873739e925c4bf7be46e1e8b93"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-webProfile8/26.0.0.5/wlp-webProfile8-26.0.0.5.zip"
    version = "26.0.5"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:26.0.0.5:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-webProfile7"
    name = "WebSphere Liberty (Web Profile 7)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-webProfile7@26.0.0.5"
    sha256 = "3dcde30fae8b35f41684c7ca84e302137490956bc1f746c35d71674aae6b8683"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-webProfile7/26.0.0.5/wlp-webProfile7-26.0.0.5.zip"
    version = "26.0.5"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/23.0.0.3/lafiles/runtime/en.html"

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
